# Generated by Django 5.0.1 on 2024-01-11 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=250)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.pergunta')),
            ],
        ),
        migrations.CreateModel(
            name='RespostaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=250)),
                ('pergunta_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.pergunta')),
                ('resposta_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.resposta')),
            ],
        ),
    ]
