# Generated by Django 5.0.1 on 2024-01-11 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resposta',
            old_name='texto',
            new_name='texto_resposta',
        ),
    ]
