# Generated by Django 4.2.9 on 2024-01-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_rename_resposta_resposta_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='texto',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='texto',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='respostausuario',
            name='usuario',
            field=models.CharField(default='usuário teste', max_length=250),
        ),
    ]
