# Generated by Django 4.2.9 on 2024-01-11 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_alter_pergunta_texto_alter_resposta_texto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respostausuario',
            old_name='pergunta_user',
            new_name='pergunta',
        ),
        migrations.RenameField(
            model_name='respostausuario',
            old_name='resposta_user',
            new_name='resposta',
        ),
    ]
