# Generated by Django 4.2.9 on 2024-01-11 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_rename_pergunta_user_respostausuario_pergunta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resposta',
            name='texto',
        ),
        migrations.AddField(
            model_name='resposta',
            name='texto_resposta',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='texto',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='respostausuario',
            name='usuario',
            field=models.CharField(max_length=250),
        ),
    ]
