# Generated by Django 4.2.9 on 2024-01-11 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_remove_resposta_texto_resposta_texto_resposta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resposta',
            old_name='texto_resposta',
            new_name='texto',
        ),
    ]
